# .github/workflows/pages.yml
name: Build & Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci
      - run: npm run build          # creates dist/

      - uses: actions/upload-pages-artifact@v2  # ← uses artifact v4 under the hood
        with:
          path: dist

      - id: deployment
        uses: actions/deploy-pages@v3
